### ISSUE TITLE
issue about running expert data

### ISSUE THREAD

**Issue by LinBornRain** [andrewliao11/gail-tf#1]
[2017-10-18 19:40:13,749] 
I run the code in PYTHON 3.6.2 and have install the mujoco and configure the mjkey successfully:

$Making new env: Ant-v1
Traceback (most recent call last):
  File "run_mujoco.py", line 56, in <module>
    main()
  File "run_mujoco.py", line 52, in main
    train(args)
  File "run_mujoco.py", line 34, in train
    task_name=task_name
TypeError: learn() got an unexpected keyword argument 'ckpt_dir'

can u help me with this issue? Appreciate it that u share GAIL code in tf BTW!

**Comment by andrewliao11** [comment]
Hi, thanks for the appreciation. 
I assume you follow the step [here](https://github.com/andrewliao11/gail-tf#sampling-expert-data). If so, I don't think this problem should occur! Can you further elaborate your problem?
Just for reminder: please navigate to ```cd $GAIL-TF/baselines/ppo1```. I haven't well organized the code in ```$GAIL-TF/baselines/trpo_mpi```

**Comment by LinBornRain** [comment]
I see. maybe thats why u use ppo instead of trpo to generate policy lol.
anyway ,I tried to use Pycharm to run in the file"run_mujoco.py" and it worked! however，following the step, and have cd to $GAIL-TF/baselines/ppo1 in the terminal, the terminal just fail to run the 'python run_mujoco.py' ,reporting like above.its kind of odd ,cause i can run the iteration in Pycharm.
I guess i can try to modify the default number in the code instead of trying the code in terminal like 'python run_mujoco.py --env_id Ant-v1' to change the environment!

**Comment by andrewliao11** [comment]
it seems that you find ur way out, lol. 
I'll first close the issue. Feel free to reopen it if needed.

**Comment by LinBornRain** [comment]
The reason that I fail to run the code is that I have installed the openai package baselines before .
Once I uninstall the package 'baselines' ,  the problem solved!!Thanks anyway!
