### ISSUE TITLE
Problem with U.save_state

### ISSUE THREAD

**Issue by wsjeon** [andrewliao11/gail-tf#11]
Hi. Thanks for your nice code. 

In `tf_util.py`, [`save_state`](https://github.com/andrewliao11/gail-tf/blob/master/gailtf/baselines/common/tf_util.py#L284-L291) is defined and used at [`trpo_mpi`](https://github.com/andrewliao11/gail-tf/blob/master/gailtf/baselines/trpo_mpi/trpo_mpi.py#L247-L248) or [`pposgd_simple`](https://github.com/andrewliao11/gail-tf/blob/master/gailtf/baselines/ppo1/pposgd_simple.py#L212-L214).

However, the problem is that, since `save_state` is inside the training loop, iterative call of `save_state` makes the size meta file increase. 

![image](https://user-images.githubusercontent.com/20200538/39095972-12b73cea-4684-11e8-9080-99caa9c9e83c.png)

I think you should modify this part by first defining `tf.Saver.save` outside the training loop.

Thanks.

**Comment by andrewliao11** [comment]
do you want to send the pull request?

**Comment by wsjeon** [comment]
Sure. Please check the [pull request](https://github.com/andrewliao11/gail-tf/pull/12).
