### ISSUE TITLE
how to play this result in mujoco

### ISSUE THREAD

**Issue by huangjiancong1** [andrewliao11/gail-tf#14]
Hi, I want to know that how to play the result in mujoco. I have finish training and i want to visualize it in mujoco. Can you share me some method?

**Comment by andrewliao11** [comment]
just call `env.render()` whenever you want to see what's going on

**Comment by huangjiancong1** [comment]
Thanks, i am trying. And i want to know what is the expert policy do?  I don't understand the first step, it seem that it generate a policy for Hopper, but i do not know this expert policy make for what task?

**Comment by andrewliao11** [comment]
if you're playing standard gym environments, the agents are basically doing locomotion
