### ISSUE TITLE
What is set_gobal_seeds means

### ISSUE THREAD

**Issue by huangjiancong1** [andrewliao11/gail-tf#17]
What is `set_gobal_seeds` means , in `ppo1/run_mujoco.py` line 2? [https://github.com/andrewliao11/gail-tf/blob/master/gailtf/baselines/ppo1/run_mujoco.py](url)

**Comment by andrewliao11** [comment]
please refer to [here](https://github.com/andrewliao11/gail-tf/blob/ad92f41c26c34e8fabc536664fb11b44f25956cf/gailtf/baselines/common/misc_util.py#L70-L78)

**Comment by andrewliao11** [comment]
i will first close the issue here. feel free to re-open it
