### ISSUE TITLE
Why "--sample_stochastic" is false in sample_trajectory task?

### ISSUE THREAD

**Issue by huangjiancong1** [andrewliao11/gail-tf#19]
Why "--sample_stochastic" is false in sample_trajectory task?
Can i use `--stochastic_policy` , [here](https://drive.google.com/drive/folders/1h3H4AY_ZBx08hz-Ct0Nxxus-V1melu1U), in imitation learning?
I don't know how to generate the expert date?
Is it the `stochastic.trpo.Hopper.0.00.pkl` in your project gail-tf is similar to `stochastic.trpo.Hopper.0.00.npz` in [openai/baselines/gail ](https://github.com/openai/baselines/blob/master/baselines/gail/run_mujoco.py)?

**Comment by andrewliao11** [comment]
yes, they are the same. and you can tried both as expert trajectories. for the question that which one is better for imitation learning, I'll say it depends on task tho

**Comment by huangjiancong1** [comment]
OK, i got it. 
But, how to generative ` deterministic.ppo.Hopper.0.00.pkl` file, use `--expert_path` behind the `main.py` ?You mean that  `stochastic.ppo.Hopper.0.00.pkl` is similar to ` deterministic.ppo.Hopper.0.00.pkl` ?
