### ISSUE TITLE
Cannot execute run_mujoco.py

### ISSUE THREAD

**Issue by takerfume** [andrewliao11/gail-tf#2]
Hi, thank you for publishing your code of GAIL.
I tried to run run_mujoco.py at the directory of ~/gail-tf/baselines/trpo_mpi 
However I got the error message below.

> [2017-10-21 17:02:39,965] Making new env: Hopper-v1
Traceback (most recent call last):
  File "run_mujoco.py", line 63, in <module>
    main()
  File "run_mujoco.py", line 59, in main
    train(args)
  File "run_mujoco.py", line 42, in train
    ckpt_dir=args.checkpoint_dir, load_model_path=args.load_model_path, task=args.task)
TypeError: learn() got an unexpected keyword argument 'sample_stochastic'

How can I solve this problem?

**Comment by andrewliao11** [comment]
I do have the argument `sample_stochastic ` [here](https://github.com/andrewliao11/gail-tf/blob/master/baselines/trpo_mpi/trpo_mpi.py#L132)
So I believe it's the problem is in your $PYTHONPATH.
I think you might encounter the same stuff as issue #1.

**Comment by takerfume** [comment]
I added $PYTHONPATH to the directory of gail-tf, and the problem is solved.
thank you very much!!
