### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by rubenvillegas** [andrewliao11/gail-tf#8]
https://github.com/andrewliao11/gail-tf/blob/adfffb64da2020146c0d4c6de661b775c47a9993/gailtf/network/adversary.py#L57

Should the line above be:

obs = (obs_ph - self.obs_rms.mean) / self.obs_rms.std

instead of

obs = (obs_ph - self.obs_rms.mean / self.obs_rms.std)

If I am confusing something, please let me know.

**Comment by andrewliao11** [comment]
good catch, can you send me the pull request for this?

**Comment by rubenvillegas** [comment]
Done. I have another question. How are the mean and std of self.obs_rms being updated? I don't see them being updated anywhere. Maybe I am missing something?

**Comment by rubenvillegas** [comment]
Done. I have another question. How are the mean and std of self.obs_rms being updated? I don't see them being updated anywhere. Maybe I am missing something?

**Comment by andrewliao11** [comment]
Hi @rubenvillegas , 
I update the running mean in the main training loop ([here](https://github.com/andrewliao11/gail-tf/blob/adfffb64da2020146c0d4c6de661b775c47a9993/gailtf/algo/trpo_mpi.py#L314))

**Comment by rubenvillegas** [comment]
Got it! Thank you. One last question. How important did you find normalizing the input to be?

**Comment by andrewliao11** [comment]
it's the convention to normalize the input. 
However, if the absolute values are required (e.g., the coordinate of the obstacles or targets), i won't normalize it.

**Comment by rubenvillegas** [comment]
Ok cool. Thanks!!
